P1=Message
P2=MessageCodes
P3=MessageFormat
P4=ShareBoardAppController
P5=LoginUI
P6=MainMenuUI
P7=Main
P8=TcpChatSrvSingleThread

all: $(P1).class $(P2).class $(P3).class $(P4).class $(P5).class $(P6).class $(P7).class $(P8).class

$(P1).class: $(P1).java
	javac $(P1).java

$(P2).class: $(P2).java
	javac $(P2).java

$(P3).class: $(P3).java
	javac $(P3).java

$(P4).class: $(P4).java
	javac $(P4).java

$(P5).class: $(P5).java
	javac $(P5).java

$(P6).class: $(P6).java
	javac $(P6).java

$(P7).class: $(P7).java
	javac $(P7).java

$(P8).class: $(P8).java
	javac $(P8).java

clean:
	rm -f *.class

